name: docs
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Build documentation
        run: |
          cp CHANGELOG.md docs/changelog.md
          sed -n '/DEFAULTS = \[/,/];/p' lib/Settings/SystemConfig.php | sed 's/^    //' > docs/system-config.php
          pip install mkdocs-material pillow cairosvg
          mkdocs gh-deploy --force
