name: e2e

on:
  push:
    branches:
      - master
      - pulsejet/*
    paths-ignore:
      - 'docs/**'
      - 'go-vod/**'
      - 'android/**'
      - 'mkdocs.yml'
      - '**.md'

env:
  APP_NAME: memories
  NODE_VERSION: 24.x
  PHP_CLI_SERVER_WORKERS: 12

jobs:
  vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Build vue app
        run: |
          npm ci
          make patch-external
          make build-js-production
          zip -r vue.zip js/

      - uses: actions/upload-artifact@v7
        with:
          name: vue.zip
          path: vue.zip

  mysql:
    runs-on: ubuntu-latest
    needs: vue

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.4']
        server-versions: ['stable34']

    services:
      mysql:
        image: mariadb:10.5
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 5

    steps:
      - name: Checkout server
        uses: actions/checkout@v6
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout the app
        uses: actions/checkout@v6
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: apps/${{ env.APP_NAME }}/package-lock.json

      - uses: actions/download-artifact@v8
        with:
          name: vue.zip

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, mysql, pdo_mysql
          coverage: none
          ini-values: >-
            opcache.enable_cli=1,
            opcache.jit=tracing,
            opcache.jit_buffer_size=64M

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          php occ maintenance:install \
            --verbose \
            --database=mysql \
            --database-name=nextcloud \
            --database-host=127.0.0.1 \
            --database-port=$DB_PORT \
            --database-user=root \
            --database-pass=rootpassword \
            --admin-user admin \
            --admin-pass password

      - name: Run tests
        env:
          NC_VERSION: ${{ matrix.server-versions }}
        run: |
          make -C apps/${{ env.APP_NAME }} e2e

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report-mysql-${{ matrix.php-versions }}-${{ matrix.server-versions }}
          path: apps/${{ env.APP_NAME }}/playwright-report

  pgsql:
    runs-on: ubuntu-latest
    needs: vue

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.4']
        server-versions: ['stable34']

    services:
      postgres:
        image: postgres
        ports:
          - 4444:5432/tcp
        env:
          POSTGRES_DB: nextcloud
          POSTGRES_PASSWORD: rootpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout server
        uses: actions/checkout@v6
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout the app
        uses: actions/checkout@v6
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: apps/${{ env.APP_NAME }}/package-lock.json

      - uses: actions/download-artifact@v8
        with:
          name: vue.zip

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, mysql, pdo_mysql
          coverage: none
          ini-values: >-
            opcache.enable_cli=1,
            opcache.jit=tracing,
            opcache.jit_buffer_size=64M

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          php occ maintenance:install \
            --verbose \
            --database=pgsql \
            --database-name=nextcloud \
            --database-host=127.0.0.1 \
            --database-port=$DB_PORT \
            --database-user=postgres \
            --database-pass=rootpassword \
            --admin-user admin \
            --admin-pass password

      - name: Run tests
        env:
          NC_VERSION: ${{ matrix.server-versions }}
        run: |
          make -C apps/${{ env.APP_NAME }} e2e

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report-pgsql-${{ matrix.php-versions }}-${{ matrix.server-versions }}
          path: apps/${{ env.APP_NAME }}/playwright-report

  sqlite:
    runs-on: ubuntu-latest
    needs: vue

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.4']
        server-versions: ['stable34']

    steps:
      - name: Checkout server
        uses: actions/checkout@v6
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout the app
        uses: actions/checkout@v6
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: apps/${{ env.APP_NAME }}/package-lock.json

      - uses: actions/download-artifact@v8
        with:
          name: vue.zip

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, mysql, pdo_mysql
          coverage: none
          ini-values: >-
            opcache.enable_cli=1,
            opcache.jit=tracing,
            opcache.jit_buffer_size=64M

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          php occ maintenance:install \
            --verbose \
            --database=sqlite \
            --database-name=nextcloud \
            --admin-user admin \
            --admin-pass password

      - name: Run tests
        env:
          NC_VERSION: ${{ matrix.server-versions }}
          NO_PLANET_DB: 1
        run: |
          make -C apps/${{ env.APP_NAME }} e2e

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report-sqlite-${{ matrix.php-versions }}-${{ matrix.server-versions }}
          path: apps/${{ env.APP_NAME }}/playwright-report
