name: tests

on:
  push:
    branches:
      - master
      - citest

env:
  APP_NAME: memories
  PHP_CLI_SERVER_WORKERS: 8

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.1']
        server-versions: ['24.0.4']
        db: ['mysql']

    services:
      mysql:
        image: mariadb:10.5
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5

    container:
      image: nextcloud:${{ matrix.server-versions }}

    steps:
      - name: Checkout the app
        uses: actions/checkout@v3
        with:
          path: apps/memories

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          php occ maintenance:install --verbose --database=mysql --database-name=nextcloud --database-host=mysql --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password

      - name: Run tests
        run: |
          ./apps/memories/ci-test.sh

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report-${{ matrix.php-versions }}-${{ matrix.server-versions }}
          path: apps/${{ env.APP_NAME }}/playwright-report

